## aprendendo panda

In [17]:
import pandas as pd

In [18]:
materiais = {'produto' : ['caderno' , 'caneta' , 'mochila'],
             'categoria' : ['papelaria' , 'papelaria' , 'acessorio'],
             'preco' : [12.50 ,2.30 ,89.90]
           }

In [19]:
df = pd.DataFrame(materiais)
df

   produto  categoria  preco
0  caderno  papelaria   12.5
1   caneta  papelaria    2.3
2  mochila  acessorio   89.9

## Lendo arquivo csv e Alterando o separador --> sep = '...'

In [22]:
df = pd.read_csv('vendas.csv',sep=';')
df

              produto  quantidade_vendida  preco_unitario
0             caderno                  34            12.5
1              caneta                 120             2.3
2             mochila                   8            89.9
3              estojo                  22            15.0
4            borracha                  60             1.5
5               lapis                  95             1.2
6           apontador                  40             3.8
7               regua                  28             4.5
8   marcador de texto                  53             6.9
9         cola bastao                  37             5.2
10            tesoura                  19             7.4
11             agenda                  15            32.0
12           fichario                  12            24.9
13            grafite                  44             2.1
14          corretivo                  26             4.3

## criação de coluna

In [27]:
df['Faturamento']= df['quantidade_vendida'] * df['preco_unitario']
df

              produto  quantidade_vendida  preco_unitario  Faturamento
0             caderno                  34            12.5        425.0
1              caneta                 120             2.3        276.0
2             mochila                   8            89.9        719.2
3              estojo                  22            15.0        330.0
4            borracha                  60             1.5         90.0
5               lapis                  95             1.2        114.0
6           apontador                  40             3.8        152.0
7               regua                  28             4.5        126.0
8   marcador de texto                  53             6.9        365.7
9         cola bastao                  37             5.2        192.4
10            tesoura                  19             7.4        140.6
11             agenda                  15            32.0        480.0
12           fichario                  12            24.9        298.8
13            grafite                  44             2.1         92.4
14          corretivo                  26             4.3        111.8

In [34]:
faturamento_total= df['Faturamento'].sum()
faturamento_medio = df ['Faturamento'].mean()
print(f'Total {faturamento_total}\nMédio {faturamento_medio}')

Total 3913.9
Médio 260.9266666666667

## Criando 'novo' csv

In [35]:
df.to_csv('vendaspython.csv',sep=';', index= False)

## Filtrando Coluna --> df['coluna']

In [23]:
df ['preco_unitario']

0     12.5
1      2.3
2     89.9
3     15.0
4      1.5
5      1.2
6      3.8
7      4.5
8      6.9
9      5.2
10     7.4
11    32.0
12    24.9
13     2.1
14     4.3
Name: preco_unitario, dtype: float64

## Contexto de Filtro --> '>=40'

In [24]:
df_qtde_40 = df[df['quantidade_vendida']>=40]
df_qtde_40

              produto  quantidade_vendida  preco_unitario
1              caneta                 120             2.3
4            borracha                  60             1.5
5               lapis                  95             1.2
6           apontador                  40             3.8
8   marcador de texto                  53             6.9
13            grafite                  44             2.1